export const HOT_ITEMS = [
  // Mounts
  "T4_MOUNT_HORSE", "T5_MOUNT_HORSE", "T6_MOUNT_HORSE", "T7_MOUNT_HORSE", "T8_MOUNT_HORSE",
  "T4_MOUNT_OX", "T5_MOUNT_OX", "T6_MOUNT_OX", "T7_MOUNT_OX", "T8_MOUNT_OX",
  "T4_MOUNT_GIANTSTAG", "T5_MOUNT_MOOSE", "T6_MOUNT_DIREBIRD", "T7_MOUNT_SWAMPDRAGON", "T8_MOUNT_DIREBULL",
  "T4_FARM_GIANTSTAG_GROWN", "T5_FARM_MOOSE_GROWN",
  
  // Bags & Capes
  "T4_BAG", "T5_BAG", "T6_BAG", "T7_BAG", "T8_BAG",
  "T4_CAPE", "T5_CAPE", "T6_CAPE", "T7_CAPE", "T8_CAPE",
  "T4_CAPEITEM_FW_MARTLOCK", "T4_CAPEITEM_FW_LYNHURST", "T4_CAPEITEM_FW_FORTSTERLING", "T4_CAPEITEM_FW_BRIDGEWATCH", "T4_CAPEITEM_FW_THETFORD", "T4_CAPEITEM_FW_CAERLEON",
  
  // Weapons - Warrior
  "T4_MAIN_SWORD", "T5_MAIN_SWORD", "T6_MAIN_SWORD",
  "T4_MAIN_AXE", "T5_MAIN_AXE", "T6_MAIN_AXE",
  "T4_MAIN_MACE", "T5_MAIN_MACE", "T6_MAIN_MACE",
  "T4_MAIN_HAMMER", "T5_MAIN_HAMMER", "T6_MAIN_HAMMER",
  "T4_2H_CLAYMORE", "T5_2H_CLAYMORE", "T6_2H_CLAYMORE",
  
  // Weapons - Hunter
  "T4_MAIN_SPEAR", "T5_MAIN_SPEAR", "T6_MAIN_SPEAR",
  "T4_2H_BOW", "T5_2H_BOW", "T6_2H_BOW",
  "T4_2H_WARBOW", "T5_2H_WARBOW", "T6_2H_WARBOW",
  "T4_2H_CROSSBOW", "T5_2H_CROSSBOW", "T6_2H_CROSSBOW",
  "T4_2H_NATURESTAFF", "T5_2H_NATURESTAFF", "T6_2H_NATURESTAFF",
  
  // Weapons - Mage
  "T4_2H_FIRESTAFF", "T5_2H_FIRESTAFF", "T6_2H_FIRESTAFF",
  "T4_2H_HOLYSTAFF", "T5_2H_HOLYSTAFF", "T6_2H_HOLYSTAFF",
  "T4_2H_CURSESTAFF", "T5_2H_CURSESTAFF", "T6_2H_CURSESTAFF",
  "T4_2H_FROSTSTAFF", "T5_2H_FROSTSTAFF", "T6_2H_FROSTSTAFF",
  "T4_2H_ARCANESTAFF", "T5_2H_ARCANESTAFF", "T6_2H_ARCANESTAFF",
  
  // Armor - Plate (Soldier)
  "T4_HEAD_PLATE_SET1", "T5_HEAD_PLATE_SET1", "T6_HEAD_PLATE_SET1",
  "T4_ARMOR_PLATE_SET1", "T5_ARMOR_PLATE_SET1", "T6_ARMOR_PLATE_SET1",
  "T4_SHOES_PLATE_SET1", "T5_SHOES_PLATE_SET1", "T6_SHOES_PLATE_SET1",
  
  // Armor - Leather (Mercenary)
  "T4_HEAD_LEATHER_SET1", "T5_HEAD_LEATHER_SET1", "T6_HEAD_LEATHER_SET1",
  "T4_ARMOR_LEATHER_SET1", "T5_ARMOR_LEATHER_SET1", "T6_ARMOR_LEATHER_SET1",
  "T4_SHOES_LEATHER_SET1", "T5_SHOES_LEATHER_SET1", "T6_SHOES_LEATHER_SET1",
  
  // Armor - Cloth (Scholar)
  "T4_HEAD_CLOTH_SET1", "T5_HEAD_CLOTH_SET1", "T6_HEAD_CLOTH_SET1",
  "T4_ARMOR_CLOTH_SET1", "T5_ARMOR_CLOTH_SET1", "T6_ARMOR_CLOTH_SET1",
  "T4_SHOES_CLOTH_SET1", "T5_SHOES_CLOTH_SET1", "T6_SHOES_CLOTH_SET1",
  
  // Consumables
  "T4_POTION_HEAL", "T6_POTION_HEAL",
  "T4_POTION_ENERGY", "T6_POTION_ENERGY",
  "T7_POTION_GIGANTIFY",
  "T8_MEAL_STEW", "T6_MEAL_STEW",
  "T7_MEAL_OMELETTE", "T5_MEAL_OMELETTE",
  
  // Gathering Tools
  "T4_TOOL_PICK", "T5_TOOL_PICK", "T6_TOOL_PICK",
  "T4_TOOL_AXE", "T5_TOOL_AXE", "T6_TOOL_AXE",
  "T4_TOOL_SICKLE", "T5_TOOL_SICKLE", "T6_TOOL_SICKLE",
  "T4_TOOL_KNIFE", "T5_TOOL_KNIFE", "T6_TOOL_KNIFE",
  "T4_TOOL_HAMMER", "T5_TOOL_HAMMER", "T6_TOOL_HAMMER",
];
